// <auto-generated />
using Hack_A_Thon.Server.src.API.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hack_A_Thon.Server.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hack_A_Thon.Server.src.API.Infastructure.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EsrbRating")
                        .HasColumnType("int");

                    b.Property<string>("GameCoverImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An open-world action RPG from the creators of Dark Souls and George R.R. Martin.",
                            Developer = "FromSoftware",
                            EsrbRating = 3,
                            GameCoverImageSrc = "",
                            Genre = "Action RPG",
                            Publisher = "Bandai Namco",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sequel to Breath of the Wild that expands on its vast open-world and puzzle-solving gameplay.",
                            Developer = "Nintendo",
                            EsrbRating = 1,
                            GameCoverImageSrc = "",
                            Genre = "Action-Adventure",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Tears of the Kingdom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
