@remoteHost = http://localhost:5093

GET {{remoteHost}}/weatherforecast/
Accept: application/json

###
GET {{remoteHost}}/VideoGames/
Accept: application/json

###
GET {{remoteHost}}/videogame/
Content-Type: application/json
{
  "Title": "Elden Ring"
}


